import Link, { LinkProps } from "next/link";
import "./globals.css";
import { getCurrentUser } from "@/lib/session";
import { UserNav } from "@/app/user-nav";
import { PropsWithChildren } from "react";
import { Separator } from "@/components/ui/separator";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const NavBarLink = (props: PropsWithChildren<LinkProps>) => {
  return (
    <Link
      {...props}
      className="px-4 py-4  text-primary/75 hover:text-primary "
    />
  );
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen w-screen bg-background text-black">
        <header className="flex justify-between mb-2 px-4 shadow">
          <nav>
            <ul className="flex font-bold">
              <li className="flex">
                <NavBarLink href="/">AddKcal</NavBarLink>
                <Separator orientation="vertical" />
              </li>
              <li className="flex">
                <NavBarLink href="/menu">Menu</NavBarLink>
                <Separator orientation="vertical" />
              </li>
              <li className="flex">
                <NavBarLink href="/history"> History</NavBarLink>
                <Separator orientation="vertical" />
              </li>
            </ul>
          </nav>
          <UserNav user={user} />
        </header>
        <main className="flex-grow flex flex-col">{children}</main>
      </body>
    </html>
  );
}
